### ISSUE TITLE
View Stash throws ArgumentOutOfRange exception 

### ISSUE THREAD

**Issue by FizzBuzz791** [EbenZhang/gitextensions#60]
I'm pretty sure I have a stash, so I'm not 100% sure what's going on here. I'm running version 2.49.99.10.
![image](https://cloud.githubusercontent.com/assets/2747764/21299457/d3e9b1c0-c5d6-11e6-88a8-638d97e6038e.png)

**Comment by EbenZhang** [comment]
Can you also post the stacktrace? It should be in the exception tab.

**Comment by FizzBuzz791** [comment]
at System.String.Substring(Int32 startIndex, Int32 length)
   at GitCommands.GitStash.FindBranch()
   at GitCommands.GitStash..ctor(String stash, Int32 i)
   at GitCommands.GitModule.GetStashes()
   at GitUI.CommandsDialogs.FormStash.Initialize()
   at GitUI.CommandsDialogs.FormStash.RefreshAll()
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by EbenZhang** [comment]
can you run `git stash list` command line and post the result?

**Comment by FizzBuzz791** [comment]
`$ git stash list`
`stash@{0}: autostash`

**Comment by EbenZhang** [comment]
Are you in middle of a rebase? or after rebase the stashed changes cannot be applied?

Check the right bottom of the GitExtensions to see if it's saying "During a rebase blahblah"/"Merge conflicts blahblahblah". If so, just solve the conflicts and commit it, otherwise, as a temporary workaround, you may use the command line to pop it from the stash.

I'll fix the code but won't be released shortly.

**Comment by FizzBuzz791** [comment]
Well, nothing about an ongoing rebase, I think that existing stash is from a rebase though. It seemed to rebase fine but left the auto-stash in place. Anyway using `git stash clear` seems to have fixed it up.

**Comment by EbenZhang** [comment]
same issue here: https://github.com/gitextensions/gitextensions/issues/2901

**Comment by EbenZhang** [comment]
Close as it has been fixed in upstream (the GitExtensions project), the fix will be delivered within next version.
